### PR TITLE
aaaaaa in perl 

### PR DESCRIPTION
**Pull request by Pikachunou**

### CODE REVIEW

**Comment by Benricheson101** [comment]
This doesn't print infinitely, it only prints once

**Review by democat3457 — CHANGES_REQUESTED** [review]
Add a 
```perl
while (1) {

}
```
that encapsulates the print statement.

**Comment by Pikachunou** [comment]
Alright, fixed that.  Thanks demo.

**Review by democat3457 — APPROVED** [review]

**Review by Benricheson101 — CHANGES_REQUESTED** [review]
remove the \n, its supposed to all be printed on one line

**Comment by Pikachunou** [comment]
Okay, fixed that, is this good enough? 
image

**Comment by Benricheson101** [comment]
looks good :+1:

**Pull request merged**
