### PR TITLE
C#

### PR DESCRIPTION
**Pull request by kushjaggi**
a in C# language

### CODE REVIEW

**Comment by Benricheson101** [comment]
we already have c#, also might help if you had the right file extension.

**Comment by kushjaggi** [comment]
Right file extension in the sense?

**Comment by Benricheson101** [comment]
c# files use the extension `.cs`

**Comment by kushjaggi** [comment]
I meant if you had why would right extension would have helped

**Comment by kushjaggi** [comment]
heck sorry i didnt realised that.

**Pull request closed without merging**
