### PR TITLE
Add GDScript

### PR DESCRIPTION
**Pull request by JezSonic**

### CODE REVIEW

**Comment by thetayloredman** [comment]
Is this infinite? That's what all the others do.

**Comment by JezSonic** [comment]
yes it is. it prints "aaaa" in new line every frame of the program

**Comment by democat3457** [comment]
is there a way to make it print on not new-line (just a nitpick, probably fine if there isn't)

**Comment by JezSonic** [comment]
> is there a way to make it print on not new-line (just a nitpick, probably fine if there isn't)

Nope, there isn't

**Pull request merged**
