### PR TITLE
A lot more aaa (Json)

### PR DESCRIPTION
**Pull request by DuckMasterAl**
This took a lot of time to get under 25mb...
There's a lot of "a"s in the format: {"aaa": 3} (aspam, numberofa)

### CODE REVIEW

**Comment by Benricheson101** [comment]
hmmmmmmmmm seems like kinda a weird format, how about formatting it just like
```json
{
  "a": "aaaaaaaaaaaa...",
  "aa": ["aaaaaaaaaaaaaaa...", "aaaaaaaaaaaaaa..."]
}
```
or something along those lines?

**Comment by DuckMasterAl** [comment]
I can *probably* do that

**Comment by thetayloredman** [comment]
But JSON is not a programming language so this is not infinite.

**Comment by DuckMasterAl** [comment]
You're missing the purpose of the repo. It's not meant to be practical in any way; it's just meant to be fun.

**Comment by democat3457** [comment]
@thetayloredman well json already exists, and so does toml

also see #106

**Comment by milanmdev** [comment]
@DuckMasterAl iirc json is already there

**Comment by democat3457** [comment]
@Benricheson101 what are your thoughts

**Comment by Benricheson101** [comment]
I don't see the need to use a weird format since there's already a JSON file.

**Pull request closed without merging**
