### PR TITLE
Faster a's once you hit 1000 (Python)

### PR DESCRIPTION
**Pull request by DuckMasterAl**
Basically, the code will spam a's even faster every thousand a's

### CODE REVIEW

**Comment by democat3457** [comment]
:eyes: you're here as well?!

**Comment by DuckMasterAl** [comment]
> 👀 you're here as well?!

Maybe and I MIGHT have made a 2gb file of a's by accident

**Comment by Benricheson101** [comment]
that would make this one not consistent with the other files...they all print only one at once, indefinitely

**Comment by DuckMasterAl** [comment]
f

**Pull request closed without merging**
