### PR TITLE
fix the lack of a real language.

### PR DESCRIPTION
**Pull request by part1cleth1ef**
the slave was whipped a number of times.

### CODE REVIEW

**Comment by democat3457** [comment]
wtf

you really can't say "nothing was harmed in the making of this pr"

**Comment by Benricheson101** [comment]
Is there a way to make this print one `a` at a time instead of just printing a bunch at once?

**Comment by part1cleth1ef** [comment]
@Benricheson101 well im too lazy to write more fetlang lmao

**Comment by part1cleth1ef** [comment]
> wtf
> 
> you really can't say "nothing was harmed in the making of this pr"
;p

**Comment by Benricheson101** [comment]
> Is there a way to make this print one `a` at a time instead of just printing a bunch at once?

When I have the time I'll try to do this.

**Review by OfficialSirH — CHANGES_REQUESTED** [review]
a while loop for printing "a"
```fet
Until Amy is dominant towards Alicia
	Make slave moan "a"
```

**Review by thenithinbalaji — APPROVED** [review]

**Comment by thenithinbalaji** [comment]
FBI Open Up

**Pull request closed without merging**
